### PR TITLE
use hex package for base32 dep

### PR DESCRIPTION
**Pull request by tsloughter**
This is needed to be able to publish dns_erlang to hex. I removed rebar2 related stuff also in hopes that it is no longer needed, rebar2 has been deprecated for awhile now.

### CODE REVIEW

**Comment by tsloughter** [comment]
Also got rid of the mix.exs file because rebar3 deps work fine with mix.

**Comment by aeden** [comment]
Could you resolve the conflicts and then I can review and merge.

**Comment by tsloughter** [comment]
Yup, will do.

**Comment by aeden** [comment]
Thank you @tsloughter!

**Pull request merged**
