### PR TITLE
add license and github link to hex info of .app.src

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by tsloughter** [comment]
Could you also make a new release?

**Comment by tsloughter** [comment]
I wonder if its not using the 'version-type: strict' since this is a forked PR.

**Comment by DXTimer** [comment]
I checked the docs for the erlef/setup-beam GH Action and their [support matrix](https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp) shows that `ubuntu-latest` (**ubuntu-22.04**) supports 24.2+. Would you mind making the changes in the workflow to change the target to **ubuntu-20.04**?

**Comment by tsloughter** [comment]
Ah. And you want that instead of bumping to 24.2+? Or even testing on 26 instead of an older version?

**Comment by tsloughter** [comment]
Well, not just 26, but 24.2, 25, 26.

**Comment by DXTimer** [comment]
I agree with you on covering more versions including 26.

**Comment by tsloughter** [comment]
The slack hook fails.

**Review by DXTimer — APPROVED** [review]
Thank you for your contribution, it looks great. I'll look into disabling the Slack job for forked PRs.

**Pull request merged**
